### ISSUE TITLE
Polytope for wedge 

### ISSUE THREAD

**Issue by fverdugo** [lssc-team/Numa.jl#13]
Is polytope giving the right nfaces for wedges?

**Comment by fverdugo** [comment]
Perhaps this is not very important right now, but it seems that `Polytope` is not giving the right information on nfaces for wedges.

```julia
wedge = Polytope(2,2,1)
@show wedge.nf_nfs
# wedge.nf_nfs = Array{Int64,1}[[1], [2], [3], [4], [5], [6], [1, 4, 7], [2, 5, 8], [3, 6, 9], [1, 2, 10], [2, 4, 11], [1, 3, 12], [2, 3, 13], [3, 4, 14], [3, 5, 15], [1, 2, 4, 5, 7, 8, 10, 11, 16], [1, 3, 4, 6, 7, 9, 12, 14, 17], [2, 3, 5, 6, 8, 9, 13, 15, 18], [1, 2, 3, 10, 12, 13, 19], [2, 3, 4, 11, 13, 14, 20], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]]
```
I would say that info about nface number 11 is wrong. Is this a bug or I am missing something @santiagobadia ?

It can also be clearly seen by writing the wedge into vtu:
```julia
writevtk(wedge,"wedge")
```
![wedge_1](https://user-images.githubusercontent.com/48508177/57144083-8724e000-6dc0-11e9-8cb9-f4ea138a242f.png)

For quads, tris, hexs, tets, and pyramids works OK. E.g. for pyramids:
```julia
pyramid = Polytope(1,1,2)
writevtk(pyramid,"pyramid")
```
![pyramid_1](https://user-images.githubusercontent.com/48508177/57144265-fbf81a00-6dc0-11e9-9c58-0b257103d910.png)

**Comment by santiagobadia** [comment]
I will take a look at this.

**Comment by santiagobadia** [comment]
Fixed
![prism](https://user-images.githubusercontent.com/39598249/57176247-06182800-6e56-11e9-904a-701f853b84f0.png)

![pyramid](https://user-images.githubusercontent.com/39598249/57176248-0ca69f80-6e56-11e9-89f0-c6a548c9e01c.png)

![hex](https://user-images.githubusercontent.com/39598249/57176250-13351700-6e56-11e9-8b8a-5eb6c50a2ac5.png)

![tet](https://user-images.githubusercontent.com/39598249/57176249-0e706300-6e56-11e9-9528-bc1b944e6efc.png)

**Comment by fverdugo** [comment]
Perfect! Nice pictures! 😎

Closing issue
