### ISSUE TITLE
Problems with coords

### ISSUE THREAD

**Issue by santiagobadia** [lssc-team/Numa.jl#14]
I am having trouble with the coordinates extracted from a trinagulation.

@fverdugo can you take a look at `FESpaceTests` l.42

```
D=2
nparts1d = 2
nparts = nparts1d*ones(Int64,D)
nparts_t = tuple(nparts...)
grid = CartesianGrid(partition=nparts_t,domain=(0,1,0,1),order=1) # domain, and order are optional
trian = triangulation(grid)
coords = cellcoordinates(trian)
size(coords)
IndexStyle(coords)
coords.lid_to_gid
coords.gid_to_val
coords.cv
length(coords)
isa(coords, AbstractArray)
```
provide reasonable values. On the other hand, coords is wrong, it only iterates till cell 2 for a 2x2 trian. Weird behaviour, it is a sub-type of AbstractArray, I can get all indices OK, but when I iterate, it does not work... The iterate for a AbstractArray is in Julia...

**Comment by fverdugo** [comment]
It is a problem related with Cartesian indexing... The commit 777caff97 should fix it. Tell me if it works.

**Comment by santiagobadia** [comment]
Working!
