### ISSUE TITLE
Style guidelines

### ISSUE THREAD

**Issue by fverdugo** [lssc-team/Numa.jl#2]
Discussion to set a consistent coding style

**Comment by fverdugo** [comment]
* Indentation 2 or 4 white spaces? I would suggest 2 to reduce line length.

* Maximum line width? It is important to set a value not very large (e.g. In python 79) in order to have good readability specially in small laptops and other portable devices

* I would strongly avoid trailing white spaces in order to not mess things up with git

**Comment by fverdugo** [comment]
* CamelCase for type names.

* Pluralized CamelCase for files that implement a type. 

* Also CamelCase for files that test a type?

**Comment by santiagobadia** [comment]
* The default indentation in Julia seems to be 4
* I have found line breaks confusing in Juno, I am trying not to break lines [see here](https://discourse.julialang.org/t/juno-julia-and-indentation/18195)
* I am not using CamelCase for tests, but not strong opinion

**Comment by santiagobadia** [comment]
It seems we should stick to  [92 characters per line](https://discourse.julialang.org/t/max-source-line-length/4883/3) in both documentation and code lines

**Comment by fverdugo** [comment]
Added CONTRIBUTING.md file where the style guidelines are described.

Closing issue.
