### ISSUE TITLE
ConstantCellArray out of bounds

### ISSUE THREAD

**Issue by santiagobadia** [lssc-team/Numa.jl#3]
In the current implementation, `ConstantCellArrays` provides the same array even when exceding its length. Is this the behavior we want?

**Comment by fverdugo** [comment]
Yes, it is like this in order to avoid a check before supplying the array. 
However, I have added a bounds check via @assert with the hope that the check is performed only
in debug mode (7b15ed1bf2bf270a65e0845b20bc28683ac4fac7). Still needed to confirm if @assert provides this behavior or not.
