### ISSUE TITLE
Geometry

### ISSUE THREAD

**Issue by fverdugo** [lssc-team/Numa.jl#9]
New API for geometry-related objects available

**Comment by fverdugo** [comment]
I have created a new API for geometry related objects. For the moment these 3 abstract types are enough:

1. `Grid` Represents a FE mesh / grid. That is, list of nodal coordinates, and for each cell, the list of node ids on the boundary of the cell. The cells of the grid can be of any order.

2. `Triangulation`. Represents a cloud of patches and provides the geomap. Minimum needed for cell-wise integration.

3. `GridGraph`. Represents the connectivity information needed to generate the dof numbers in a FE space.

Usage:

```julia
using Numa.Geometry
using Numa.Geometry.Cartesian # defines the struct CartesianGrid
grid = CartesianGrid(partition=(10,20),domain=(0,1,0,1),order=1) # domain, and order are optional
trian = triangulation(grid) # Generates the Triangulation associated with this grid
graph = gridgraph(grid) # Generates the GridGraph associated with this grid.
phi = geomap(trian)
@show celltovefs(graph) # Show vefs for each cell
@show veftocells(graph) # Show cells around each vef
```
The FE space can already be rewritten in terms of this API. @santiagobadia, do I try to do this (i.e., to substitute `Mesh` and `StructHexMesh` for this new API), or do you prefer to do it yourself?

**Comment by santiagobadia** [comment]
Ok, I can do it!

**Comment by santiagobadia** [comment]
I have put some comments in the module. You can take them into consideration if you want.

I have changed the FESpace, but still, 

- [ ] FESpace must have a `CellValue{RefFE}` instead of only one RefFE.

**Comment by fverdugo** [comment]
I have answered, the comments in line in the code. You can easily see them with git diff.

> - [ ] FESpace must have a `CellValue{RefFE}` instead of only one RefFE.

Note that this would be type unstable since the template parameter is not a concrete type. The way to go IMHO is to have a tuple of RefFE and then a CellValue{Int} that indexes it.

**Comment by santiagobadia** [comment]
Yes, I wrote it fast ut I wanted to templatize FESpace with respect to typeof(reffe_array).
If what you wrote works, perfect.

**Comment by fverdugo** [comment]
Just do
```julia
(Numa) pkg> up UnstructuredGrids
```
and then remove the if in https://github.com/lssc-team/Numa.jl/blob/659af7b407cee9fe8896338a1edc897f172cf25b/src/Geometry/Unstructured.jl#L76
and the assertion in https://github.com/lssc-team/Numa.jl/blob/659af7b407cee9fe8896338a1edc897f172cf25b/src/Geometry/Geometry.jl#L216

**Comment by santiagobadia** [comment]
Perfect! I have now cells too...

**Comment by fverdugo** [comment]
This issue has become obsolete. Closing it.
